FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build-env
ENV DOTNET_USE_POLLING_FILE_WATCHER 1
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./


ENTRYPOINT dotnet watch run --project TranslatorNet.csproj